### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-payment#17]
```
INFO [09:13:42] [_install_cordova_app:202]   * Building rogerthat-payment
npm WARN @angular/core@4.2.6 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/common@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/compiler@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/forms@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/http@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of rxjs@5.4.0 but none was installed.
npm WARN ionic-angular@3.5.0-201706292025 requires a peer of zone.js@0.8.12 but none was installed.

up to date in 5.325s

> payments@0.0.1 build:prepare /Users/bart/tmp/cordova/build/rogerthat-payment
> node tools/prepare_production_build.js


> payments@0.0.1 build:prod /Users/bart/tmp/cordova/build/rogerthat-payment
> ionic-app-scripts build --prod --iscordovaserve --externalIpRequired --nobrowser --enableLint false && node tools/finish_production_build.js

[09:13:53]  ionic-app-scripts 2.0.0 
[09:13:53]  build prod started ... 
[09:13:53]  clean started ... 
[09:13:53]  clean finished in 2 ms 
[09:13:53]  copy started ... 
[09:13:53]  ngc started ... 
[09:14:05]  ngc finished in 11.75 s 
[09:14:05]  preprocess started ... 
[09:14:05]  deeplinks started ... 
[09:14:05]  deeplinks finished in 380 ms 
[09:14:06]  optimization started ... 
[09:14:06]  copy finished in 12.63 s 
[09:14:19]  optimization finished in 13.11 s 
[09:14:19]  preprocess finished in 13.72 s 
[09:14:19]  webpack started ... 
[09:14:34]  webpack finished in 15.63 s 
[09:14:34]  sass started ... 
[09:14:34]  uglifyjs started ... 
[09:14:36]  sass finished in 1.25 s 
[09:14:36]  cleancss started ... 
[09:14:38]  cleancss finished in 1.99 s 
[09:14:51]  uglifyjs finished in 16.73 s 
[09:14:51]  postprocess started ... 
[09:14:51]  postprocess finished in 17 ms 
[09:14:51]  build prod finished in 57.91 s 
Copying resources
Coloring splash screen
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/bart/tmp/cordova/build/rogerthat-payment/colors.scss'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at colorSplashScreen (/Users/bart/tmp/cordova/build/rogerthat-payment/tools/finish_production_build.js:60:21)
    at ncp (/Users/bart/tmp/cordova/build/rogerthat-payment/tools/finish_production_build.js:43:34)
    at cb (/Users/bart/tmp/cordova/build/rogerthat-payment/node_modules/ncp/lib/ncp.js:255:37)
    at WriteStream.<anonymous> (/Users/bart/tmp/cordova/build/rogerthat-payment/node_modules/ncp/lib/ncp.js:133:14)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:587:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! payments@0.0.1 build:prod: `ionic-app-scripts build --prod --iscordovaserve --externalIpRequired --nobrowser --enableLint false && node tools/finish_production_build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the payments@0.0.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bart/.npm/_logs/2017-08-03T07_14_52_718Z-debug.log
Traceback (most recent call last):
  File "release-scripts/prepare_build.py", line 1056, in <module>
    cordova.install_cordova_plugins(APP_ID, cordova_plugins, get_cordova_apps(), doc['COLORS'])
  File "/Users/bart/mobicage/git/rogerthat-android-client/release-scripts/cordova.py", line 111, in install_cordova_plugins
    install_cordova_apps(app_id, cordova_apps, colors)
  File "/Users/bart/mobicage/git/rogerthat-android-client/release-scripts/cordova.py", line 137, in install_cordova_apps
    _install_cordova_app(app_id, cordova_app, colors)
  File "/Users/bart/mobicage/git/rogerthat-android-client/release-scripts/cordova.py", line 212, in _install_cordova_app
    subprocess.check_call(['npm', 'run', 'build:prod'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build:prod']' returned non-zero exit status 1
```

**Comment by lucasvanhalst** [comment]
Fixed
