### ISSUE TITLE
Create/import/export wallet [8h]

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-payment#9]
use getSeed to export it

**Comment by lucasvanhalst** [comment]
Can't test this as I cannot create a wallet
```
07-04 14:43:35.624 com.mobicage.rogerth.at D/MC: UI   | Failed to processGetAddress
                                                 javax.crypto.IllegalBlockSizeException
                                                     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
                                                     at javax.crypto.Cipher.doFinal(Cipher.java:1939)
                                                     at com.mobicage.rogerthat.util.security.SecurityUtils.deviceDecryptValue(SecurityUtils.java:439)
                                                     at com.mobicage.rogerthat.util.security.SecurityUtils.getAddress(SecurityUtils.java:346)
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.processGetAddress(RogerthatPlugin.java:970)
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.processGetAddress(RogerthatPlugin.java:961)
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.onActivityResult(RogerthatPlugin.java:885)
                                                     at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
                                                     at com.mobicage.rogerthat.cordova.CordovaActionScreenActivity.onActivityResult(CordovaActionScreenActivity.java:196)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
                                                     at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                  Caused by: android.security.KeyStoreException: Unknown error
                                                     at android.security.KeyStore.getKeyStoreException(KeyStore.java:1097)
                                                     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
                                                     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
                                                     at javax.crypto.Cipher.doFinal(Cipher.java:1939) 
                                                     at com.mobicage.rogerthat.util.security.SecurityUtils.deviceDecryptValue(SecurityUtils.java:439) 
                                                     at com.mobicage.rogerthat.util.security.SecurityUtils.getAddress(SecurityUtils.java:346) 
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.processGetAddress(RogerthatPlugin.java:970) 
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.processGetAddress(RogerthatPlugin.java:961) 
                                                     at com.mobicage.rogerthat.cordova.RogerthatPlugin.onActivityResult(RogerthatPlugin.java:885) 
                                                     at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152) 
                                                     at com.mobicage.rogerthat.cordova.CordovaActionScreenActivity.onActivityResult(CordovaActionScreenActivity.java:196) 
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:7226) 
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:4477) 
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524) 
                                                     at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

**Comment by lucasvanhalst** [comment]
Done: export
In progress: import
